---
title: "Multivariate post-processing"
author: "Jieyu Chen"
date: "10/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r start, include=FALSE}
library(scoringRules)
library(lubridate)
library(crch)
library(tidyverse)
library(ggplot2)
library(ensembleBMA)
load("E:/0-TIGGE_ECMWF_Germany/ecmwf_ens_subset_unipp.RData")
load("E:/0-TIGGE_ECMWF_Germany/ecmwf_ens_subset_mvpp.RData")

```


```{r score, echo=TRUE, message=FALSE, warning=FALSE}
print("Univariate post-processing: CRPS")
summary(crps_ens)
summary(crps_emosloc_fix9y)
summary(crps_emosloc_rolling28d)
summary(crps_emosglob_fix9y)

print("Univariate post-processing: rank/PIT histograms")
hist(rank_ens)
hist(pit_emosloc_fix9y)
hist(pit_emosloc_rolling28d)
hist(pit_emosglob_fix9y)

print("Multivariate post-processing: Energy score")
summary(es_ens)
summary(es_emos)
summary(es_ecc)
summary(es_ssh)
summary(es_gca)

print("Multivariate post-processing: Variogram score p=0.5")
summary(vs_ens)
summary(vs_emos)
summary(vs_ecc)
summary(vs_ssh)
summary(vs_gca)

```

```{r rankhist, echo=FALSE, message=FALSE, warning=FALSE}

print("Raw ensemble members:")
verifRankHist(ens_fc_t2m_mv_subset[,6:55],ens_fc_t2m_mv_subset[,3])
print("EMOS-Q, ECC-Q, SSH-Q:")
verifRankHist(emos_eval_all[,6:55],emos_eval_all[,3])
print("GCA:")
verifRankHist(gca_eval_all[,6:55],gca_eval_all[,3])

print("Multivariate rank histograms using average ranks:")

multi_rank_ens = rep(NA, length(eval_dates))
for(day_id in 1:length(eval_dates)){
  # print(day_id)
  today <- eval_dates[day_id]
  
  data_today <- subset(data_eval_all, date == today)
  # ecc_data_today <- subset(ecc_eval_all, date == today)
  # ssh_data_today <- subset(ssh_eval_all, date == today)
  # gca_data_today <- subset(gca_eval_all, date == today)
  # emos_data_today <- subset(emos_eval_all, date == today)
  
  observations = data_today[,3]
  forecasts = data_today[,6:55]
  
  trajectory_rank <- apply(cbind(observations, forecasts), 1, function(x) 
    rank(x, ties = "random"))
  average_rank = apply(trajectory_rank, 1, mean)
  obs_average_rank = rank(average_rank, ties = "random")[1]

  multi_rank_ens[day_id] = obs_average_rank
}
hist(multi_rank_ens)

multi_rank_emos = rep(NA, length(eval_dates))
for(day_id in 1:length(eval_dates)){
  # print(day_id)
  today <- eval_dates[day_id]
  
  # data_today <- subset(data_eval_all, date == today)
  # ecc_data_today <- subset(ecc_eval_all, date == today)
  # ssh_data_today <- subset(ssh_eval_all, date == today)
  # gca_data_today <- subset(gca_eval_all, date == today)
  emos_data_today <- subset(emos_eval_all, date == today)
  
  observations = emos_data_today[,3]
  forecasts = emos_data_today[,6:55]
  
  trajectory_rank <- apply(cbind(observations, forecasts), 1, function(x) 
    rank(x, ties = "random"))
  average_rank = apply(trajectory_rank, 1, mean)
  obs_average_rank = rank(average_rank, ties = "random")[1]

  multi_rank_emos[day_id] = obs_average_rank
}
hist(multi_rank_emos)

multi_rank_ecc = rep(NA, length(eval_dates))
for(day_id in 1:length(eval_dates)){
  # print(day_id)
  today <- eval_dates[day_id]

  # data_today <- subset(data_eval_all, date == today)
  ecc_data_today <- subset(ecc_eval_all, date == today)
  # ssh_data_today <- subset(ssh_eval_all, date == today)
  # gca_data_today <- subset(gca_eval_all, date == today)
  # emos_data_today <- subset(emos_eval_all, date == today)
  
  observations = ecc_data_today[,3]
  forecasts = ecc_data_today[,6:55]
  
  trajectory_rank <- apply(cbind(observations, forecasts), 1, function(x) 
    rank(x, ties = "random"))
  average_rank = apply(trajectory_rank, 1, mean)
  obs_average_rank = rank(average_rank, ties = "random")[1]

  multi_rank_ecc[day_id] = obs_average_rank
}
hist(multi_rank_ecc)

multi_rank_ssh = rep(NA, length(eval_dates))
for(day_id in 1:length(eval_dates)){
  # print(day_id)
  today <- eval_dates[day_id]

  # data_today <- subset(data_eval_all, date == today)
  # ecc_data_today <- subset(ecc_eval_all, date == today)
  ssh_data_today <- subset(ssh_eval_all, date == today)
  # gca_data_today <- subset(gca_eval_all, date == today)
  # emos_data_today <- subset(emos_eval_all, date == today)
  
  observations = ssh_data_today[,3]
  forecasts = ssh_data_today[,6:55]
  
  trajectory_rank <- apply(cbind(observations, forecasts), 1, function(x) 
    rank(x, ties = "random"))
  average_rank = apply(trajectory_rank, 1, mean)
  obs_average_rank = rank(average_rank, ties = "random")[1]

  multi_rank_ssh[day_id] = obs_average_rank
}
hist(multi_rank_ssh)

multi_rank_gca = rep(NA, length(eval_dates))
for(day_id in 1:length(eval_dates)){
  # print(day_id)
  today <- eval_dates[day_id]

  # data_today <- subset(data_eval_all, date == today)
  # ecc_data_today <- subset(ecc_eval_all, date == today)
  # ssh_data_today <- subset(ssh_eval_all, date == today)
  gca_data_today <- subset(gca_eval_all, date == today)
  # emos_data_today <- subset(emos_eval_all, date == today)
  
  observations = gca_data_today[,3]
  forecasts = gca_data_today[,6:55]
  
  trajectory_rank <- apply(cbind(observations, forecasts), 1, function(x) 
    rank(x, ties = "random"))
  average_rank = apply(trajectory_rank, 1, mean)
  obs_average_rank = rank(average_rank, ties = "random")[1]

  multi_rank_gca[day_id] = obs_average_rank
}
hist(multi_rank_gca)



```